name: Upload

on:
  push:
    branches:
      - master

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
        persist-credentials: false

      - uses: harupy/push-kaggle-kernel@master
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        with:
          slug: ${{ github.sha }}
          title: ${{ github.sha }}
          code_file: ./src/eda.ipynb
          language: python
          kernel_type: notebook
          is_private: false
          competition_sources: |
            nfl-big-data-bowl-2021
